// Code generated by MockGen. DO NOT EDIT.
// Source: mbx/template (interfaces: TemplateFetcher,TemplateSender,TemplateRepo)

// Package template is a generated GoMock package.
package template

import (
	context "context"
	models "mbx/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTemplateFetcher is a mock of TemplateFetcher interface.
type MockTemplateFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateFetcherMockRecorder
}

// MockTemplateFetcherMockRecorder is the mock recorder for MockTemplateFetcher.
type MockTemplateFetcherMockRecorder struct {
	mock *MockTemplateFetcher
}

// NewMockTemplateFetcher creates a new mock instance.
func NewMockTemplateFetcher(ctrl *gomock.Controller) *MockTemplateFetcher {
	mock := &MockTemplateFetcher{ctrl: ctrl}
	mock.recorder = &MockTemplateFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateFetcher) EXPECT() *MockTemplateFetcherMockRecorder {
	return m.recorder
}

// GetTemplates mocks base method.
func (m *MockTemplateFetcher) GetTemplates(arg0 context.Context) ([]models.SavedTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplates", arg0)
	ret0, _ := ret[0].([]models.SavedTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplates indicates an expected call of GetTemplates.
func (mr *MockTemplateFetcherMockRecorder) GetTemplates(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplates", reflect.TypeOf((*MockTemplateFetcher)(nil).GetTemplates), arg0)
}

// ListMessagingServices mocks base method.
func (m *MockTemplateFetcher) ListMessagingServices(arg0 context.Context) ([]models.MessagingService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessagingServices", arg0)
	ret0, _ := ret[0].([]models.MessagingService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessagingServices indicates an expected call of ListMessagingServices.
func (mr *MockTemplateFetcherMockRecorder) ListMessagingServices(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessagingServices", reflect.TypeOf((*MockTemplateFetcher)(nil).ListMessagingServices), arg0)
}

// MockTemplateSender is a mock of TemplateSender interface.
type MockTemplateSender struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateSenderMockRecorder
}

// MockTemplateSenderMockRecorder is the mock recorder for MockTemplateSender.
type MockTemplateSenderMockRecorder struct {
	mock *MockTemplateSender
}

// NewMockTemplateSender creates a new mock instance.
func NewMockTemplateSender(ctrl *gomock.Controller) *MockTemplateSender {
	mock := &MockTemplateSender{ctrl: ctrl}
	mock.recorder = &MockTemplateSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateSender) EXPECT() *MockTemplateSenderMockRecorder {
	return m.recorder
}

// CreateTemplate mocks base method.
func (m *MockTemplateSender) CreateTemplate(arg0 context.Context, arg1 models.CreateTemplateDTO) (*models.SavedTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", arg0, arg1)
	ret0, _ := ret[0].(*models.SavedTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockTemplateSenderMockRecorder) CreateTemplate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockTemplateSender)(nil).CreateTemplate), arg0, arg1)
}

// MockTemplateRepo is a mock of TemplateRepo interface.
type MockTemplateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateRepoMockRecorder
}

// MockTemplateRepoMockRecorder is the mock recorder for MockTemplateRepo.
type MockTemplateRepoMockRecorder struct {
	mock *MockTemplateRepo
}

// NewMockTemplateRepo creates a new mock instance.
func NewMockTemplateRepo(ctrl *gomock.Controller) *MockTemplateRepo {
	mock := &MockTemplateRepo{ctrl: ctrl}
	mock.recorder = &MockTemplateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateRepo) EXPECT() *MockTemplateRepoMockRecorder {
	return m.recorder
}

// GetTemplates mocks base method.
func (m *MockTemplateRepo) GetTemplates(arg0 context.Context) ([]models.SavedTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplates", arg0)
	ret0, _ := ret[0].([]models.SavedTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplates indicates an expected call of GetTemplates.
func (mr *MockTemplateRepoMockRecorder) GetTemplates(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplates", reflect.TypeOf((*MockTemplateRepo)(nil).GetTemplates), arg0)
}

// SaveTemplate mocks base method.
func (m *MockTemplateRepo) SaveTemplate(arg0 context.Context, arg1 models.SavedTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTemplate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTemplate indicates an expected call of SaveTemplate.
func (mr *MockTemplateRepoMockRecorder) SaveTemplate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTemplate", reflect.TypeOf((*MockTemplateRepo)(nil).SaveTemplate), arg0, arg1)
}
