// Code generated by MockGen. DO NOT EDIT.
// Source: mbx/persistence/postgres (interfaces: TemplateRepository)

// Package postgres is a generated GoMock package.
package postgres

import (
	context "context"
	models "mbx/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTemplateRepository is a mock of TemplateRepository interface.
type MockTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateRepositoryMockRecorder
}

// MockTemplateRepositoryMockRecorder is the mock recorder for MockTemplateRepository.
type MockTemplateRepositoryMockRecorder struct {
	mock *MockTemplateRepository
}

// NewMockTemplateRepository creates a new mock instance.
func NewMockTemplateRepository(ctrl *gomock.Controller) *MockTemplateRepository {
	mock := &MockTemplateRepository{ctrl: ctrl}
	mock.recorder = &MockTemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateRepository) EXPECT() *MockTemplateRepositoryMockRecorder {
	return m.recorder
}

// GetTemplates mocks base method.
func (m *MockTemplateRepository) GetTemplates(arg0 context.Context) ([]models.SavedTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplates", arg0)
	ret0, _ := ret[0].([]models.SavedTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplates indicates an expected call of GetTemplates.
func (mr *MockTemplateRepositoryMockRecorder) GetTemplates(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplates", reflect.TypeOf((*MockTemplateRepository)(nil).GetTemplates), arg0)
}

// SaveTemplate mocks base method.
func (m *MockTemplateRepository) SaveTemplate(arg0 context.Context, arg1 models.SavedTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTemplate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTemplate indicates an expected call of SaveTemplate.
func (mr *MockTemplateRepositoryMockRecorder) SaveTemplate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTemplate", reflect.TypeOf((*MockTemplateRepository)(nil).SaveTemplate), arg0, arg1)
}
