// Code generated by MockGen. DO NOT EDIT.
// Source: mbx/persistence/postgres (interfaces: SchedulerRepository)

// Package postgres is a generated GoMock package.
package postgres

import (
	context "context"
	models "mbx/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSchedulerRepository is a mock of SchedulerRepository interface.
type MockSchedulerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerRepositoryMockRecorder
}

// MockSchedulerRepositoryMockRecorder is the mock recorder for MockSchedulerRepository.
type MockSchedulerRepositoryMockRecorder struct {
	mock *MockSchedulerRepository
}

// NewMockSchedulerRepository creates a new mock instance.
func NewMockSchedulerRepository(ctrl *gomock.Controller) *MockSchedulerRepository {
	mock := &MockSchedulerRepository{ctrl: ctrl}
	mock.recorder = &MockSchedulerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchedulerRepository) EXPECT() *MockSchedulerRepositoryMockRecorder {
	return m.recorder
}

// GetPending mocks base method.
func (m *MockSchedulerRepository) GetPending(arg0 context.Context, arg1 int) ([]models.ScheduledMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPending", arg0, arg1)
	ret0, _ := ret[0].([]models.ScheduledMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPending indicates an expected call of GetPending.
func (mr *MockSchedulerRepositoryMockRecorder) GetPending(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPending", reflect.TypeOf((*MockSchedulerRepository)(nil).GetPending), arg0, arg1)
}

// MarkAsFailed mocks base method.
func (m *MockSchedulerRepository) MarkAsFailed(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailed", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailed indicates an expected call of MarkAsFailed.
func (mr *MockSchedulerRepositoryMockRecorder) MarkAsFailed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailed", reflect.TypeOf((*MockSchedulerRepository)(nil).MarkAsFailed), arg0, arg1, arg2)
}

// MarkAsSent mocks base method.
func (m *MockSchedulerRepository) MarkAsSent(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsSent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsSent indicates an expected call of MarkAsSent.
func (mr *MockSchedulerRepositoryMockRecorder) MarkAsSent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsSent", reflect.TypeOf((*MockSchedulerRepository)(nil).MarkAsSent), arg0, arg1)
}

// Save mocks base method.
func (m *MockSchedulerRepository) Save(arg0 context.Context, arg1 *models.ScheduledMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSchedulerRepositoryMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSchedulerRepository)(nil).Save), arg0, arg1)
}
