// Code generated by MockGen. DO NOT EDIT.
// Source: schedules/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "mbx/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 models.ScheduledMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// FindById mocks base method.
func (m *MockRepository) FindById(arg0 context.Context, arg1 uuid.UUID) (*models.ScheduledMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", arg0, arg1)
	ret0, _ := ret[0].(*models.ScheduledMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockRepositoryMockRecorder) FindById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockRepository)(nil).FindById), arg0, arg1)
}

// ListUpcoming mocks base method.
func (m *MockRepository) ListUpcoming(arg0 context.Context, arg1 time.Duration) ([]models.ScheduledMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUpcoming", arg0, arg1)
	ret0, _ := ret[0].([]models.ScheduledMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUpcoming indicates an expected call of ListUpcoming.
func (mr *MockRepositoryMockRecorder) ListUpcoming(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUpcoming", reflect.TypeOf((*MockRepository)(nil).ListUpcoming), arg0, arg1)
}
