// Code generated by MockGen. DO NOT EDIT.
// Source: mbx/messaging (interfaces: MessageSender,MessageFetcher,SchedulerRepo)

// Package messaging is a generated GoMock package.
package messaging

import (
	context "context"
	models "mbx/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	openapi "github.com/twilio/twilio-go/rest/api/v2010"
)

// MockMessageSender is a mock of MessageSender interface.
type MockMessageSender struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSenderMockRecorder
}

// MockMessageSenderMockRecorder is the mock recorder for MockMessageSender.
type MockMessageSenderMockRecorder struct {
	mock *MockMessageSender
}

// NewMockMessageSender creates a new mock instance.
func NewMockMessageSender(ctrl *gomock.Controller) *MockMessageSender {
	mock := &MockMessageSender{ctrl: ctrl}
	mock.recorder = &MockMessageSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSender) EXPECT() *MockMessageSenderMockRecorder {
	return m.recorder
}

// CancelMessage mocks base method.
func (m *MockMessageSender) CancelMessage(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelMessage indicates an expected call of CancelMessage.
func (mr *MockMessageSenderMockRecorder) CancelMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelMessage", reflect.TypeOf((*MockMessageSender)(nil).CancelMessage), arg0, arg1)
}

// Send mocks base method.
func (m *MockMessageSender) Send(arg0 context.Context, arg1 models.WhatsappBody) (*openapi.ApiV2010Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1)
	ret0, _ := ret[0].(*openapi.ApiV2010Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockMessageSenderMockRecorder) Send(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMessageSender)(nil).Send), arg0, arg1)
}

// SendTemplate mocks base method.
func (m *MockMessageSender) SendTemplate(arg0 context.Context, arg1 models.WhatsappTemplate) (*openapi.ApiV2010Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTemplate", arg0, arg1)
	ret0, _ := ret[0].(*openapi.ApiV2010Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTemplate indicates an expected call of SendTemplate.
func (mr *MockMessageSenderMockRecorder) SendTemplate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTemplate", reflect.TypeOf((*MockMessageSender)(nil).SendTemplate), arg0, arg1)
}

// MockMessageFetcher is a mock of MessageFetcher interface.
type MockMessageFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockMessageFetcherMockRecorder
}

// MockMessageFetcherMockRecorder is the mock recorder for MockMessageFetcher.
type MockMessageFetcherMockRecorder struct {
	mock *MockMessageFetcher
}

// NewMockMessageFetcher creates a new mock instance.
func NewMockMessageFetcher(ctrl *gomock.Controller) *MockMessageFetcher {
	mock := &MockMessageFetcher{ctrl: ctrl}
	mock.recorder = &MockMessageFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageFetcher) EXPECT() *MockMessageFetcherMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockMessageFetcher) GetMessages(arg0 context.Context, arg1 time.Time) ([]models.SentMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", arg0, arg1)
	ret0, _ := ret[0].([]models.SentMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockMessageFetcherMockRecorder) GetMessages(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockMessageFetcher)(nil).GetMessages), arg0, arg1)
}

// GetScheduledMessages mocks base method.
func (m *MockMessageFetcher) GetScheduledMessages(arg0 context.Context, arg1 time.Time) ([]models.SentMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledMessages", arg0, arg1)
	ret0, _ := ret[0].([]models.SentMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledMessages indicates an expected call of GetScheduledMessages.
func (mr *MockMessageFetcherMockRecorder) GetScheduledMessages(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledMessages", reflect.TypeOf((*MockMessageFetcher)(nil).GetScheduledMessages), arg0, arg1)
}

// MockSchedulerRepo is a mock of SchedulerRepo interface.
type MockSchedulerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerRepoMockRecorder
}

// MockSchedulerRepoMockRecorder is the mock recorder for MockSchedulerRepo.
type MockSchedulerRepoMockRecorder struct {
	mock *MockSchedulerRepo
}

// NewMockSchedulerRepo creates a new mock instance.
func NewMockSchedulerRepo(ctrl *gomock.Controller) *MockSchedulerRepo {
	mock := &MockSchedulerRepo{ctrl: ctrl}
	mock.recorder = &MockSchedulerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchedulerRepo) EXPECT() *MockSchedulerRepoMockRecorder {
	return m.recorder
}

// GetPending mocks base method.
func (m *MockSchedulerRepo) GetPending(arg0 context.Context, arg1 int) ([]models.ScheduledMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPending", arg0, arg1)
	ret0, _ := ret[0].([]models.ScheduledMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPending indicates an expected call of GetPending.
func (mr *MockSchedulerRepoMockRecorder) GetPending(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPending", reflect.TypeOf((*MockSchedulerRepo)(nil).GetPending), arg0, arg1)
}

// MarkAsFailed mocks base method.
func (m *MockSchedulerRepo) MarkAsFailed(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailed", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailed indicates an expected call of MarkAsFailed.
func (mr *MockSchedulerRepoMockRecorder) MarkAsFailed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailed", reflect.TypeOf((*MockSchedulerRepo)(nil).MarkAsFailed), arg0, arg1, arg2)
}

// MarkAsSent mocks base method.
func (m *MockSchedulerRepo) MarkAsSent(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsSent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsSent indicates an expected call of MarkAsSent.
func (mr *MockSchedulerRepoMockRecorder) MarkAsSent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsSent", reflect.TypeOf((*MockSchedulerRepo)(nil).MarkAsSent), arg0, arg1)
}

// Save mocks base method.
func (m *MockSchedulerRepo) Save(arg0 context.Context, arg1 *models.ScheduledMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSchedulerRepoMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSchedulerRepo)(nil).Save), arg0, arg1)
}
